# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kitek's Page
tagline:          Dziennik programisty / webdeveloper'a
description:      'Kitek.pl - strona domowa Marcina Kitowicza - blog, PHP, MySQL, JavaScript, NodeJS i wiele innych'
url:              http://kitek.pl

author:
  name:           'Marcin Kitowicz'
  url:            http://www.kitek.pl
  gplus:          https://plus.google.com/+MarcinKitowicz	

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/kitek
