# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kitek's Page
tagline:          Dziennik programisty / webdeveloper'a
description:      'Lorem ipsum'
url:              http://kitek.github.io

author:
  name:           'Marcin Kitowicz'
  url:            http://www.kitek.pl

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/kitek
